=begin
#tradewatch.io

#Financial market data for Developers

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for tradewatch::AccountApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountApi' do
  before do
    # run before each test
    @api_instance = tradewatch::AccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountApi' do
    it 'should create an instance of AccountApi' do
      expect(@api_instance).to be_instance_of(tradewatch::AccountApi)
    end
  end

  # unit tests for getUsage
  # Usage statistics
  # Get the usage statistics of your API account
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [AccountUsageStatisticsInterval] :interval 
  # @return [Object]
  describe 'getUsage test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
