=begin
#tradewatch.io

#Financial market data for Developers

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.11.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for tradewatch::ApiUsageDataTransfer
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe tradewatch::ApiUsageDataTransfer do
  let(:instance) { tradewatch::ApiUsageDataTransfer.new }

  describe 'test an instance of ApiUsageDataTransfer' do
    it 'should create an instance of ApiUsageDataTransfer' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(tradewatch::ApiUsageDataTransfer)
    end
  end

  describe 'test attribute "request"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "response"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
