=begin
#tradewatch.io

#Financial market data for Developers

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for tradewatch::CommodityTypesList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe tradewatch::CommodityTypesList do
  let(:instance) { tradewatch::CommodityTypesList.new }

  describe 'test an instance of CommodityTypesList' do
    it 'should create an instance of CommodityTypesList' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(tradewatch::CommodityTypesList)
    end
  end

  describe 'test attribute "items"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
