=begin
#tradewatch.io

#Financial market data for Developers

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for tradewatch::Country
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe tradewatch::Country do
  let(:instance) { tradewatch::Country.new }

  describe 'test an instance of Country' do
    it 'should create an instance of Country' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(tradewatch::Country)
    end
  end

end
