=begin
#tradewatch.io

#Financial market data for Developers

The version of the OpenAPI document: 3.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0-SNAPSHOT

=end

require 'date'
require 'time'

module tradewatch
  class SymbolsListMode
    FULL = "full".freeze
    BASE = "base".freeze

    def self.all_vars
      @all_vars ||= [FULL, BASE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if SymbolsListMode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #SymbolsListMode"
    end
  end
end
